version: '3.8'

services:
    php:
        build:
            context: ./php
        volumes:
            - ./../:/var/www
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony_app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - php

volumes:
    db_data:
